### ISSUE TITLE
If current temp > target temp and speed = max speed, decrease power to lower temps.

### ISSUE THREAD

**Issue by overcookedpanda** [Steambot33/HiveOS-NVIDIA-GPU-autofan-2.0#2]
In nvOC and forks, the auto fan/temp control script will lower the PL of the card to ensure the target temp is accomplished if the fans are at their max setting and the temperate remains above, I believe this is a very useful feature and was wondering if it could be implemented into your HiveOS autofan control.

**Comment by anton-kuptsov** [comment]
It's present in this version.

**Comment by overcookedpanda** [comment]
Could you give instructions on replacing the one in HiveOS with one that includes power management?  Would it be as simple as just replacing the script? I haven't looked at the code fully, but figured you would know the easiest way to accomplish that.
